# Path to your oh-my-zsh installation.
  export ZSH="$HOME/.oh-my-zsh"

export HOSTNAME=`hostname`

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# ZSH_THEME="robbyrussell"
ZSH_THEME="agnosterc"

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(vi-mode git history history-substring-search)

# conditional plugin loading based on host. Must be sourced before running
# oh-my-zsh.sh
case "$HOSTNAME" in
  mu)
    ;;
  atlantis)
    ;;
  hy-brasil)
    ;;
  shangri-la)
    plugins+=(ripgrep zsh-autosuggestions httpie zsh-syntax-highlighting)
    ;;
  Aarons-MBP)
    plugins+=(osx)
    ;;
  *)
    ;;
esac

# User configuration
export PATH="$HOME/bin:$PATH"

# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

export EDITOR='nvim'

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
alias zshconfig="nvim $HOME/.zshrc"
alias ohmyzsh="nvim $HOME/.oh-my-zsh/oh-my-zsh.sh"
alias tmux='tmux -2'
alias gdv='git difftool'

# OTHER

# Typing EOF (CTRL+D) will not exit interactive sessions
set -o ignoreeof

# setting to 15 ms to support using neovim as editor when typing vv in
# zsh-vi-mode. Was previously set to 1 ms. There is a reason for this but I
# can't remember why.
export KEYTIMEOUT=15

# disable ctrl-s and ctrl-q
stty -ixon

# RIPGREP config
export RG_COMMAND_BASE='rg --ignore-file ~/.ignore --hidden --follow --colors=path:fg:white --colors=line:fg:white --colors=match:fg:yellow'
export FD_COMMAND_BASE='fd --ignore-file ~/.ignore --hidden --follow'

# FZF
[ -f $HOME/.fzf.zsh ] && source $HOME/.fzf.zsh
export FZF_DEFAULT_COMMAND="$FD_COMMAND_BASE -t f"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_PREVIEW_PREVIEW_BAT_THEME='gruvbox-material'
_fzf_compgen_path() {
  eval ${FD_COMMAND_BASE} --exclude ".git" . "$1"
}
export FZF_DEFAULT_OPTS="
  -m --history $HOME/.fzf.history --bind ctrl-a:select-all,alt-n:next-history,alt-p:previous-history,ctrl-n:down,ctrl-p:up
  --color hl:11,prompt:14,marker:02,pointer:04,info:14
"

# colored man pages
man() {
  LESS_TERMCAP_md=$'\e[01;36m' \
  LESS_TERMCAP_me=$'\e[0m' \
  LESS_TERMCAP_se=$'\e[0m' \
  LESS_TERMCAP_so=$'\e[0;47;30m' \
  LESS_TERMCAP_ue=$'\e[0m' \
  LESS_TERMCAP_us=$'\e[01;32m' \
  command man "$@"
}

# gruvbox
GBPALETTE=$HOME/dotfiles/gruvbox_256palette.sh
if [[ -a $GBPALETTE ]]; then
  sh $GBPALETTE
fi

# todo.txt
if [[ -a /usr/bin/todo.sh ]]; then
  alias t='todo.sh'
  export TODOTXT_DEFAULT_ACTION=ls
  compdef -d todo.sh
  autoload bashcompinit
  bashcompinit
  source $HOME/.todo/todo_completion
fi

# GULP COLOR REPLACEMENT
#
# Gulp uses colors that are incompatible with GOTHAM\
# theme. Only use this if using the GOTHAM theme.

function gulpc() {
  gulp "$@" --color | sed -r 's/\[90m/[93m/g'
}

DIRCOLORS="dircolors"

# environment settings and scripts for specific hosts
case "$HOSTNAME" in
  mu)
    ;;
  atlantis)
    ;;
  hy-brasil)
    export PATH="$HOME/.gem/ruby/2.4.0/bin:$PATH"
    export ARCHFLAGS="-arch i386"
    ;;
  shangri-la)
    if [[ -a $HOME/.shangri-la.zshrc ]]; then
      . $HOME/.shangri-la.zshrc
    fi
    ;;
  Aarons-MBP)
    if [[ -a $HOME/.mac.zshrc ]]; then
      . $HOME/.mac.zshrc
    fi
    ;;
  *)
    ;;
esac

# dircolors
eval $($DIRCOLORS $HOME/.dir_colors)


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
